### ISSUE TITLE
Terminating app due to uncaught exception

### ISSUE THREAD

**Issue by oenama** [rlaguilar/MultilineTextField#1]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x1028c3c00 of class MultilineTextField.MultilineTextField was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x170239e40> (
<NSKeyValueObservance 0x17044fff0: Observer: 0x175672a80, Key path: font, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x17044f8a0>
<NSKeyValueObservance 0x1704507a0: Observer: 0x170c6a180, Key path: textContainerInset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x170450560>
)'
*** First throw call stack:
(0x18b0d01c0 0x189b0855c 0x18b0d0108 0x18bb1ddf4 0x18b0bfe30 0x18afb1c70 0x189b21fe0 0x190f17134 0x191010cb8 0x1913fa818 0x189b06f10 0x189b136e0 0x189b13744 0x1912b6fe0 0x190f17154 0x190ff58a4 0x18b0bfe30 0x18afb1c70 0x1912631b4 0x189b06f10 0x189b136e0 0x189b13744 0x1912b6fe0 0x190f17154 0x190ff5f38 0x1910a99e0 0x189b21fe0 0x18afa9db8 0x18b07bb20 0x18afaa048 0x18ca2d198
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by rlaguilar** [comment]
Hi @Amaneo 
Can you please provide some clues about how are you using the `MultilineTextField`? I mean, under what conditions this crash happens? In addition to that if you can provide a sample project it would be great.

**Comment by oenama** [comment]
I did add it using storyboard, Added a UITextView and set its custom class to MultilineTextField. the view which has my textView is pushed when I try to pop to the previous view controller the app crashes

**Comment by rlaguilar** [comment]
@oenama Ok, i'll try to reproduce the problem. Thanks.
